CREATE TABLE `reportes_mantenimiento` (
  `folio` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cambio_aceite` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cambio_filtro_aceite` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cambio_filtro_aire` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cambio_separador_aceite` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revision_valvula_admision` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revision_valvula_descarga` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `limpieza_radiador` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revision_bandas_correas` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revision_fugas_aire` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revision_fugas_aceite` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revision_conexiones_electricas` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revision_presostato` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revision_manometros` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lubricacion_general` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `limpieza_general` enum('Sí','No') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comentarios_generales` longtext COLLATE utf8mb4_unicode_ci,
  `comentario_cliente` longtext COLLATE utf8mb4_unicode_ci,
  `fecha_creacion` datetime DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`folio`),
  CONSTRAINT `reportes_mantenimiento_ibfk_1` FOREIGN KEY (`folio`) REFERENCES `ordenes_servicio` (`folio`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
